# Generated by Django 6.0 on 2025-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Легковой', 'Легковой'), ('Внедорожник', 'Внедорожник'), ('Электромобиль', 'Электромобиль'), ('JDM', 'JDM')], max_length=20),
        ),
    ]
